package view;

import controller.UserController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import utils.Utils;

/**
 * @author tiago
 */
public class FrListaUser extends javax.swing.JFrame {

    public FrListaUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        textFiltro = new javax.swing.JTextField();
        cbOrderBy = new javax.swing.JComboBox<>();
        btnListarUsuarios = new javax.swing.JButton();
        cbFiltro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnExcluir2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("CONSULTAR USUÁRIOS");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        gridUsuarios.setBackground(new java.awt.Color(220, 220, 220));
        gridUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "Data de nascimento", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(gridUsuarios);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 648, 265));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFiltro.setBackground(new java.awt.Color(220, 220, 220));
        textFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiltroActionPerformed(evt);
            }
        });
        textFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFiltroKeyPressed(evt);
            }
        });
        jPanel3.add(textFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 214, -1));

        cbOrderBy.setBackground(new java.awt.Color(220, 220, 220));
        cbOrderBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código ASC", "Código DESC", "Nome A-Z", "Nome Z-A", "Email A-Z", "Email Z-A" }));
        cbOrderBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrderByActionPerformed(evt);
            }
        });
        jPanel3.add(cbOrderBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 150, -1));

        btnListarUsuarios.setBackground(new java.awt.Color(220, 220, 220));
        btnListarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListarUsuarios.setText("FILTRAR");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });
        btnListarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnListarUsuariosKeyPressed(evt);
            }
        });
        jPanel3.add(btnListarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 30));

        cbFiltro.setBackground(new java.awt.Color(220, 220, 220));
        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome iniciando com ", "Nome contendo", "Email iniciando com", "Email contendo" }));
        cbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroActionPerformed(evt);
            }
        });
        cbFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbFiltroKeyPressed(evt);
            }
        });
        jPanel3.add(cbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 150, -1));

        jLabel2.setText("Filtros:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 37, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("FILTROS");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("BUSCAR POR");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("ORDENAR");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 480, 130));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        btnExcluir2.setBackground(new java.awt.Color(220, 220, 220));
        btnExcluir2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir2.setText("EXCLUIR");
        btnExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar2.setBackground(new java.awt.Color(220, 220, 220));
        btnEditar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar2.setText("EDITAR");
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 51));
        jLabel9.setText("FUNÇÕES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir2)
                    .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Preview.png"))); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cbFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbFiltroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listar();
        }
    }//GEN-LAST:event_cbFiltroKeyPressed

    private void cbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltroActionPerformed

    private void btnListarUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnListarUsuariosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listar();
        }
    }//GEN-LAST:event_btnListarUsuariosKeyPressed

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        listar();
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void cbOrderByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrderByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrderByActionPerformed

    private void textFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFiltroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listar();
        }
    }//GEN-LAST:event_textFiltroKeyPressed

    private void textFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFiltroActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (gridUsuarios.getSelectedRow() != -1) {
            int posicaoSelecionada = gridUsuarios.getSelectedRow();
            String textoCelulaId = gridUsuarios.getValueAt(posicaoSelecionada, 0).toString();
            int id_usuario = Integer.parseInt(textoCelulaId);

            User usu = new User();
            usu.setId_usuario(id_usuario);

            FrAltUser frAltUser = new FrAltUser();

            frAltUser.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    listar();  // Atualiza a tabela chamando o método listar
                }
            });

            frAltUser.setVisible(true);
            frAltUser.setUser(usu); // passando o usuário para a outra tela

        } else {
            JOptionPane.showMessageDialog(null, "Para editar um usuário, selecione uma linha.");

        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (gridUsuarios.getSelectedRow() != -1) {
            int posicaoSelecionada = gridUsuarios.getSelectedRow();
            String textoCelulaId = gridUsuarios.getValueAt(posicaoSelecionada, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir este usuário?");

            if (confirm == JOptionPane.YES_OPTION) {

                int id_usuario = Integer.parseInt(textoCelulaId);

                UserController controller = new UserController();
                boolean deuCerto = controller.deletarUsuario(id_usuario);

                if (deuCerto) {
                    JOptionPane.showMessageDialog(null, "Usuário de código " + id_usuario + " excluído com sucesso!");
                    listar();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ação cancelada.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Para excluir um usuário, selecione uma linha.");

        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    public void listar() {
        DefaultTableModel model = (DefaultTableModel) gridUsuarios.getModel();
        model.setNumRows(0);

        UserController controller = new UserController();

        int tipoFiltro = cbFiltro.getSelectedIndex();
        String filtro = textFiltro.getText();
        int orderBy = cbOrderBy.getSelectedIndex();

        List<User> listaUsers = controller.listaUsuarios(tipoFiltro, filtro, orderBy);

        if (!listaUsers.isEmpty()) { // método retornou algum resultado

            for (User usu : listaUsers) {

                Object[] linha = {
                    usu.getId_usuario(),
                    usu.getNome(),
                    usu.getEmail(),
                    Utils.converterDateToString(usu.getDataNasc()),
                    usu.ativoToString()
                };
                model.addRow(linha);

            }

        } else { // nenhum resultado
            Object[] linha = {
                "Nenhum resultado para esta pesquisa."
            };
            model.addRow(linha);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrListaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrListaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrListaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrListaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrListaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnExcluir2;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<String> cbOrderBy;
    private javax.swing.JTable gridUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textFiltro;
    // End of variables declaration//GEN-END:variables
}
